mod 'puppet-nginx', '1.0.0'
mod 'puppetlabs/concat'
mod 'puppetlabs/stdlib'
mod 'pltraining-dockeragent', '0.0.16'
mod 'garethr/docker'
mod 'puppetlabs/apt'
mod 'puppetlabs/translate'
mod 'puppetlabs/powershell'
mod 'puppetlabs/reboot'
mod 'puppetlabs/docker'
